:page-layout: getting-started
:page-guide-id: handling-failures
:page-liquid:
:include_dir: ../../../../src/test/java/guides

Mutiny提供了几个操作符来处理失败的情况

记住，失败是由观察到的流发送的终结事件，表示发生了 _坏事_ 。
失败后，将不再接收到任何元素。

当一个失败事件被接收时，您可以：

* 向下游传播这个事件(这是默认行为)，或者
* 将这个异常转换为另一类型的异常, 或者
* 通过切换到另一个流的方式，或者传递一个回退元素到下游，或者直接结束来从失败中恢复，或者
* 重试 (这将在下一篇指南中介绍)

如果您不处理失败事件，它将传播到下游，直到某个阶段来处理失败，或者直接到达终端的订阅者

IMPORTANT: 对于 `Mutiny` 一个失败会导致取消订阅 , 这意味着您将不再接收到任何元素。
`retry` 操作符允许您重新进行订阅并且继续接收元素。

== 观测失败

当产生一个失败时，执行一些自定义操作可能很有用。例如，您可以记录故障：
举个例子，您可以记录这个失败：

[source, java, indent=0]
----
include::{include_dir}/HandlingFailuresTest.java[tag=invoke]
----

TIP: 您还可以使用 `onFailure().call(Function<Throwable, Uni<?>)` 执行异步操作。
当传递的函数返回的 `Uni` 产生元素时，之前接收到的异常将向下游传播。

== 转换失败类型

另一个对失败有用的操作是将失败转化为 _更有意义_ 的失败。
一般来说，您可以将低层的异常（比如 `IOException` ）转为业务异常（`ServiceUnavailableException` ）：

[source, java, indent=0]
----
include::{include_dir}/HandlingFailuresTest.java[tag=transform]
----

== 使用回退元素从失败中恢复

通常情况下，您希望从失败中恢复。
第一种方法时通过使用一个元素来替换来从失败中恢复：

[source, java, indent=0]
----
include::{include_dir}/HandlingFailuresTest.java[tag=recover-item]
----

第二种方式是通过接收一个 `Supplier` 对象来计算获得到回退元素。
对于下游来说，它不会失败而是获取到这个回退元素

然而，请不要忘记失败代表了结束！
所以，对于 `Multi`，下游会接收到回退元素，然后接收到流结束的信号，因为（上游）无法产生更多的元素了

== 失败时结束

当观测一个 `Multi` 时，您可以将失败替换为流结束的信号

[source, java, indent=0]
----
include::{include_dir}/HandlingFailuresTest.java[tag=recover-completion]
----

下游将不会看到这个失败，只能看到一个结束的信号

== 切换到另一个流

On failure, you may want to switch to an alternate stream.
When the failure is received, it subscribes to this other stream and propagates the items from this stream instead:
当失败时，您可能想要切换到另一个代替的流。
当收到一个失败时，它将订阅另一个流并且传播从这个流产生的元素到下游

[source, java, indent=0]
----
include::{include_dir}/HandlingFailuresTest.java[tag=recover-switch]
----
`recoverWithUni` 和 `recoverWithMulti` 方法用给定的流替换已经失败的流

这个回退的流产生的事件类型必须和原来上游产生的类型一致

